export const SECTOR_ROTATION_CALCULATION_SERVICE =
  'SECTOR_ROTATION_CALCULATION_SERVICE';
export const SECTOR_ROTATION_DATA_READ_REPOSITORY =
  'SECTOR_ROTATION_DATA_READ_REPOSITORY';
export const SECTOR_ROTATION_DATA_WRITE_REPOSITORY =
  'SECTOR_ROTATION_DATA_WRITE_REPOSITORY';
export const SECTOR_ROTATION_PERSISTENCE_SERVICE =
  'SECTOR_ROTATION_PERSISTENCE_SERVICE';
