export const CONSOLIDATION_SCREENER_SERVICE = 'CONSOLIDATION_SCREENER_SERVICE';
export const CONSOLIDATION_RESULT_REPOSITORY =
  'CONSOLIDATION_RESULT_REPOSITORY';
export const CONSOLIDATION_ANALYSIS_SERVICE = 'CONSOLIDATION_ANALYSIS_SERVICE';
