export const CONSOLIDATION_SCREENER_SERVICE = 'CONSOLIDATION_SCREENER_SERVICE';
export const CONSOLIDATION_RESULT_REPOSITORY =
  'CONSOLIDATION_RESULT_REPOSITORY';
export const CONSOLIDATION_ANALYSIS_SERVICE = 'CONSOLIDATION_ANALYSIS_SERVICE';
export const RS_RATING_REPOSITORY = 'RS_RATING_REPOSITORY';
export const RS_RATING_COMPUTATION_SERVICE = 'RS_RATING_COMPUTATION_SERVICE';
export const RS_RATING_SCREENER_SERVICE = 'RS_RATING_SCREENER_SERVICE';
