export const LEADER_SCAN_REPOSITORY = Symbol('LEADER_SCAN_REPOSITORY');
export const LEADER_SCAN_SCREENER_SERVICE = Symbol(
  'LEADER_SCAN_SCREENER_SERVICE',
);
export const LEADER_SCAN_ANALYSIS_SERVICE = Symbol(
  'LEADER_SCAN_ANALYSIS_SERVICE',
);
