export const MARKET_DATA_SERVICE = 'MARKET_DATA_SERVICE';
export const SCREENER_SERVICE = 'SCREENER_SERVICE';
export const FUNDAMENTAL_SERVICE = 'FUNDAMENTAL_SERVICE';
export const MARKET_DATA_CACHE_REPOSITORY = 'MARKET_DATA_CACHE_REPOSITORY';
