export const MARKET_DATA_SERVICE = 'MARKET_DATA_SERVICE';
export const MARKET_DATA_CACHE_REPOSITORY = 'MARKET_DATA_CACHE_REPOSITORY';
export const COMPANY_PROFILE_SERVICE = 'COMPANY_PROFILE_SERVICE';
export const CHART_DATA_SERVICE = 'CHART_DATA_SERVICE';
export const CACHED_MARKET_DATA_SERVICE = 'CACHED_MARKET_DATA_SERVICE';
