export const WATCHLIST_MONITORING_WRITE_REPOSITORY =
  'WATCHLIST_MONITORING_WRITE_REPOSITORY';
export const WATCHLIST_MONITORING_READ_REPOSITORY =
  'WATCHLIST_MONITORING_READ_REPOSITORY';
export const BREAKOUT_DETECTION_SERVICE = 'BREAKOUT_DETECTION_SERVICE';
