export const MARKET_BREADTH_REPOSITORY = 'MARKET_BREADTH_REPOSITORY';
export const MARKET_BREADTH_UNIVERSE_SERVICE =
  'MARKET_BREADTH_UNIVERSE_SERVICE';
export const MARKET_BREADTH_ANALYSIS_SERVICE =
  'MARKET_BREADTH_ANALYSIS_SERVICE';
export const MARKET_BREADTH_MARKET_DATA_SERVICE =
  'MARKET_BREADTH_MARKET_DATA_SERVICE';
